package com.projectirp.institutemanagementsystem.Services;

import com.projectirp.institutemanagementsystem.DTOs.TeacherRegistrationDto;
import com.projectirp.institutemanagementsystem.Models.TeacherProfile;
import com.projectirp.institutemanagementsystem.Models.Users;
import com.projectirp.institutemanagementsystem.Repositories.TeacherRepo;
import com.projectirp.institutemanagementsystem.Repositories.UserRepo;
import com.projectirp.institutemanagementsystem.Utilities.InstituteRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.management.relation.Relation;
import java.util.List;


@Service
public class AdminService {

    @Autowired
    private UserRepo userRepo;
    @Autowired
    private TeacherRepo teacherRepo;
    @Autowired
    private UserService userService;


    public List<String> dashboard() {
        return userRepo.findByAdminName();
    }


    public String registerTeacher(TeacherRegistrationDto dto) {
        try {
            Users teacherUser = new Users(
                    dto.getFullName(), dto.getContact(), dto.getEmail(), dto.getPassword(), InstituteRoles.TEACHER, dto.isActive()
            );

            Users savedUser = userService.userRegistration(teacherUser);  // user has created but not the teacher profile...

            TeacherProfile teacherProfile = new TeacherProfile(
                    null, // id (generated by DB)
                    savedUser, // userId (set after saving User)
                    dto.getFullName(),
                    dto.getTeacherRegId(),
                    dto.getCnic(),
                    dto.getQualification(),
                    dto.getSalary(),
                    dto.getJoiningDate(),
                    dto.getSubjects(),
                    dto.getClasses(),
                    dto.getContact(),
                    dto.getAddress(),
                    dto.getAge(),
                    null, // createdAt
                    null  // updatedAt
            );

            teacherRepo.save(teacherProfile);

            return "Teacher Registered " + teacherProfile.getTeacherFullName();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public List<TeacherProfile> fetchAllTeachers() {
        try {
            return teacherRepo.findAll();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public List<String> fetchTeachersByClass(int teacherClass) {
        try {
            return teacherRepo.fetchTeachersByClass(teacherClass);
        } catch (RuntimeException e) {
            throw new RuntimeException(e);
        }
    }

    public List<String> fetchTeachersByClassAndSubject(int teacherClass, String teacherSubject) {
        try {
            return teacherRepo.fetchTeachersByClassAndSubject(teacherClass, teacherSubject);
        } catch (RuntimeException e) {
            throw new RuntimeException(e);
        }
    }

    @Transactional
    public TeacherProfile updateTeacher(String teacherRegId, TeacherProfile teacherProfile) {
        try {
            TeacherProfile curTeacher = teacherRepo.findTeacherByRegId(teacherRegId);
            if (curTeacher == null) {
                throw new RuntimeException("No Teacher Found with RegID = " + teacherRegId);
            } else {
                curTeacher.setTeacherFullName(teacherProfile.getTeacherFullName());
                curTeacher.setTeacherRegId(teacherProfile.getTeacherRegId());
                curTeacher.setCnic(teacherProfile.getCnic());
                curTeacher.setQualification(teacherProfile.getQualification());
                curTeacher.setSalary(teacherProfile.getSalary());
                curTeacher.setJoiningDate(teacherProfile.getJoiningDate());
//                curTeacher.setSubjects(teacherProfile.getSubjects());
//                curTeacher.setClasses(teacherProfile.getClasses());
                curTeacher.setContact(teacherProfile.getContact());
                curTeacher.setAddress(teacherProfile.getAddress());
                curTeacher.setAge(teacherProfile.getAge());
                
                curTeacher.getSubjects().clear();
                if (teacherProfile.getSubjects() != null) {
                    curTeacher.getSubjects().addAll(teacherProfile.getSubjects());
                }
                curTeacher.getClasses().clear(); // Triggers DELETE for old classes
                if (teacherProfile.getClasses() != null) {
                    curTeacher.getClasses().addAll(teacherProfile.getClasses()); // Triggers INSERT for new ones
                }

            }
            return teacherRepo.save(curTeacher);
        } catch (RuntimeException e) {
            throw new RuntimeException(e);
        }
    }

    public String deleteTeacher(String teacherRegId) {
        TeacherProfile existingTeacher = teacherRepo.findTeacherByRegId(teacherRegId);
        Users existingTeacherUserId = existingTeacher.getUserId();
//        existingTeacherUserId.getUserId();  // Long UserID
        if (existingTeacherUserId != null) {
            userRepo.deleteById(existingTeacherUserId.getUserId()); // del from the user as well
            teacherRepo.deleteTeacherByRegId(teacherRegId);
        }
        return teacherRepo.deleteTeacherByRegId(teacherRegId);
    }
}
