package com.projectirp.institutemanagementsystem.Services;

import com.projectirp.institutemanagementsystem.DTOs.TeacherRegistrationDto;
import com.projectirp.institutemanagementsystem.Models.TeacherProfile;
import com.projectirp.institutemanagementsystem.Models.Users;
import com.projectirp.institutemanagementsystem.Repositories.TeacherRepo;
import com.projectirp.institutemanagementsystem.Repositories.UserRepo;
import com.projectirp.institutemanagementsystem.Utilities.InstituteRoles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.management.relation.Relation;
import java.util.List;


@Service
public class AdminService {

    @Autowired
    private UserRepo userRepo;
    @Autowired
    private TeacherRepo teacherRepo;
    @Autowired
    private UserService userService;


    public List<String> dashboard() {
        return userRepo.findByAdminName();
    }


    public String registerTeacher(TeacherRegistrationDto dto) {
        try {
            Users teacherUser = new Users(
                    dto.getFullName(), dto.getContact(), dto.getEmail(), dto.getPassword(), InstituteRoles.TEACHER, dto.isActive()
            );

            Users savedUser = userService.userRegistration(teacherUser);  // user has created but not the teacher profile...

            TeacherProfile teacherProfile = new TeacherProfile(
                    null, // id (generated by DB)
                    savedUser, // userId (set after saving User)
                    dto.getFullName(),
                    dto.getTeacherRegId(),
                    dto.getCnic(),
                    dto.getQualification(),
                    dto.getSalary(),
                    dto.getJoiningDate(),
                    dto.getSubjects(),
                    dto.getClasses(),
                    dto.getContact(),
                    dto.getAddress(),
                    dto.getAge(),
                    null, // createdAt
                    null  // updatedAt
            );

            teacherRepo.save(teacherProfile);

            return "Teacher Registered " + teacherProfile.getTeacherFullName();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public List<TeacherProfile> fetchAllTeachers() {
        try {
            return teacherRepo.findAll();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public List<String> fetchTeachersByClass(int teacherClass) {
        try {
            return teacherRepo.fetchTeachersByClass(teacherClass);
        } catch (RuntimeException e) {
            throw new RuntimeException(e);
        }
    }
}
