spring.application.name=InstituteResourcePlanning


# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/IRP
spring.datasource.username=postgres
spring.datasource.password=0000

## Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=irp
spring.security.user.password=111

# Server settings
server.port=8080

# Fixed Error:: JSON parse error: Cannot map `null` into type `boolean` (set DeserializationConfig.DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES to 'false' to allow)]
spring.jackson.deserialization.fail-on-null-for-primitives=false

# JWT
jwt.secret=7f8a9b2c3d4e5f60918293q4b6c6d7e8f901234567890absfFGSHAHFABBFGUGWSdef12345678
# 7 days in ms
jwt.expiration=604800000